
import { onSchedule } from "firebase-functions/v2/scheduler";
import * as logger from "firebase-functions/logger";
import { db } from "../firebase";
import { format, startOfMonth } from "date-fns";
import { FieldValue } from "firebase-admin/firestore";

exports.generateMonthlySalaryExpenses = onSchedule("0 0 1 * *", async (event) => {
    logger.log("Running monthly salary expense generation job.");
    const now = new Date();
    const currentMonth = format(now, 'yyyy-MM');
    const firstDayOfMonth = format(startOfMonth(now), 'yyyy-MM-dd');
    
    const propertiesSnapshot = await db.collection("properties").get();
    for (const propertyDoc of propertiesSnapshot.docs) {
        const propertyId = propertyDoc.id;
        
        const staffQuery = db.collection('staff')
            .where('propertyId', '==', propertyId)
            .where('status', '==', 'Active') // Corrected from 'Actif'
            .where('salary', '>', 0);
        const staffSnapshot = await staffQuery.get();

        if (staffSnapshot.empty) {
            logger.log(`No active staff with salary found for property ${propertyId}. Skipping.`);
            continue;
        }

        let totalSalary = 0;
        const staffCount = staffSnapshot.size;
        staffSnapshot.forEach(doc => {
            totalSalary += doc.data().salary;
        });

        const expenseId = `salary_${currentMonth}_${propertyId}`;
        const expenseRef = db.doc(`expenses/${expenseId}`);
        const docSnap = await expenseRef.get();

        if (!docSnap.exists) {
            const expenseData = {
                expenseName: `Salaires du personnel`,
                expenseType: 'Fixe',
                category: 'Salaires',
                amount: totalSalary,
                date: firstDayOfMonth,
                notes: `Généré automatiquement pour les salaires de ${staffCount} employés.`,
                propertyId: propertyId,
                autoGenerated: true,
                createdAt: FieldValue.serverTimestamp(),
            };
            await expenseRef.set(expenseData);
            logger.log(`Scheduled salary expense for ${staffCount} staff in property ${propertyId}. Total: ${totalSalary}`);
        } else {
            logger.log(`Salary expense for ${currentMonth} in property ${propertyId} already exists. Skipping.`);
        }
    }
    logger.log("Finished monthly salary expense generation job.");
});
