
import { onCall, HttpsError } from "firebase-functions/v2/https";
import * as logger from "firebase-functions/logger";
import { db } from "../firebase";
import { format, startOfMonth } from "date-fns";
import { FieldValue } from "firebase-admin/firestore";

export const manuallyTriggerSalaryExpenses = onCall({ region: 'europe-west1', memory: '512MiB' }, async (request) => {
    if (!request.auth) {
        throw new HttpsError("unauthenticated", "Must be authenticated.");
    }
    
    const adminUid = request.auth.uid;
    const adminDoc = await db.collection("staff").doc(adminUid).get();
    
    if (!adminDoc.exists || adminDoc.data()?.permissions?.finance !== true) {
        throw new HttpsError("permission-denied", "Must have finance permissions.");
    }
    const propertyId = adminDoc.data()?.propertyId;
    if (!propertyId) {
        throw new HttpsError("failed-precondition", "User is not associated with a property.");
    }

    logger.log("Manually triggering monthly salary expense generation job for property", propertyId);

    const now = new Date();
    const currentMonth = format(now, 'yyyy-MM');
    const firstDayOfMonth = format(startOfMonth(now), 'yyyy-MM-dd');
    
    const staffQuery = db.collection('staff')
        .where('propertyId', '==', propertyId)
        .where('status', '==', 'Active') // Corrected from 'Actif'
        .where('salary', '>', 0);
    const staffSnapshot = await staffQuery.get();

    if (staffSnapshot.empty) {
        logger.log(`No active staff with salary found for property ${propertyId}.`);
        return { success: true, message: "No active staff with salaries found to import.", expensesCreated: 0 };
    }

    let totalSalary = 0;
    const staffCount = staffSnapshot.size;
    const staffPositions = new Set<string>();
    staffSnapshot.forEach(doc => {
        const data = doc.data();
        totalSalary += data.salary;
        if(data.role) {
            staffPositions.add(data.role);
        }
    });

    const expenseId = `salary_${currentMonth}_${propertyId}`;
    const expenseRef = db.doc(`expenses/${expenseId}`);
    const docSnap = await expenseRef.get();

    if (!docSnap.exists) {
        const expenseData = {
            expenseName: `Salaires du personnel`,
            expenseType: 'Fixe',
            category: 'Salaires',
            amount: totalSalary,
            date: firstDayOfMonth,
            notes: `Salaires pour ${staffCount} employés. Positions: ${Array.from(staffPositions).join(', ')}.`,
            propertyId: propertyId,
            autoGenerated: true,
            createdAt: FieldValue.serverTimestamp(),
        };
        await expenseRef.set(expenseData);
        logger.log(`Created manual salary expense for ${staffCount} staff in property ${propertyId}. Total: ${totalSalary}`);
        return { success: true, message: `A single expense record was created for ${staffCount} salaries.`, expensesCreated: 1 };
    } else {
        logger.log(`Salary expense for ${currentMonth} in property ${propertyId} already exists. Skipping.`);
        return { success: true, message: "Salary expense for this month already exists.", expensesCreated: 0 };
    }
});
