
import type { Timestamp } from 'firebase/firestore';

export type ExpenseType = 'Fixe' | 'Variable';
export const expenseTypes: ExpenseType[] = ['Fixe', 'Variable'];

export type ExpenseCategory = 'Loyer' | 'Salaires' | 'Fournitures' | 'Maintenance' | 'Électricité' | 'Eau' | 'Divers';
export const expenseCategories: ExpenseCategory[] = ['Loyer', 'Salaires', 'Fournitures', 'Maintenance', 'Électricité', 'Eau', 'Divers'];

export interface Expense {
  id: string; // Firestore document ID
  propertyId: string;
  expenseName: string;
  expenseType: ExpenseType;
  category: ExpenseCategory;
  amount: number;
  date: string; // Stored as ISO string "yyyy-MM-dd"
  notes?: string;
  autoGenerated?: boolean; // To identify salary expenses
  
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}
